FROM oven/bun:1.3.13-alpine AS deps

WORKDIR /app

RUN apk add --no-cache build-base python3 libusb-dev eudev-dev

COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile

FROM deps AS builder

WORKDIR /app

ARG NEXT_PUBLIC_BE_URL=https://api.memechan.gg
ARG NEXT_PUBLIC_CHART_HISTORICAL_PRICES_ENDPOINT=https://api.memechan.gg/chart
ARG NEXT_PUBLIC_CHART_CURRENT_PRICE_ENDPOINT=https://api.memechan.gg/price
ARG NEXT_PUBLIC_CHART_REALTIME_RELOAD_INTERVAL=3000
ARG NEXT_PUBLIC_CHART_PRICE_DIGITS_AFTER_COMMA=10
ARG NEXT_PUBLIC_SDK_ENV=production
ARG NEXT_PUBLIC_USE_MOCK_DATA=false
ARG NEXT_PUBLIC_VCHAN_TOKEN_ADDRESS=
ARG NEXT_PUBLIC_VECHAN_TOKEN_ADDRESS=
ARG NEXT_PUBLIC_MEMECHAN_PROGRAM_ID=
ARG NEXT_PUBLIC_MEMECHAN_PROGRAM_ID_V2=
ARG NEXT_PUBLIC_MEMECHAN_PROGRAM_ID_STAKING=
ARG CHART_CONTRACT_NAME=USD

ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_BE_URL=$NEXT_PUBLIC_BE_URL
ENV NEXT_PUBLIC_CHART_HISTORICAL_PRICES_ENDPOINT=$NEXT_PUBLIC_CHART_HISTORICAL_PRICES_ENDPOINT
ENV NEXT_PUBLIC_CHART_CURRENT_PRICE_ENDPOINT=$NEXT_PUBLIC_CHART_CURRENT_PRICE_ENDPOINT
ENV NEXT_PUBLIC_CHART_REALTIME_RELOAD_INTERVAL=$NEXT_PUBLIC_CHART_REALTIME_RELOAD_INTERVAL
ENV NEXT_PUBLIC_CHART_PRICE_DIGITS_AFTER_COMMA=$NEXT_PUBLIC_CHART_PRICE_DIGITS_AFTER_COMMA
ENV NEXT_PUBLIC_SDK_ENV=$NEXT_PUBLIC_SDK_ENV
ENV NEXT_PUBLIC_USE_MOCK_DATA=$NEXT_PUBLIC_USE_MOCK_DATA
ENV NEXT_PUBLIC_VCHAN_TOKEN_ADDRESS=$NEXT_PUBLIC_VCHAN_TOKEN_ADDRESS
ENV NEXT_PUBLIC_VECHAN_TOKEN_ADDRESS=$NEXT_PUBLIC_VECHAN_TOKEN_ADDRESS
ENV NEXT_PUBLIC_MEMECHAN_PROGRAM_ID=$NEXT_PUBLIC_MEMECHAN_PROGRAM_ID
ENV NEXT_PUBLIC_MEMECHAN_PROGRAM_ID_V2=$NEXT_PUBLIC_MEMECHAN_PROGRAM_ID_V2
ENV NEXT_PUBLIC_MEMECHAN_PROGRAM_ID_STAKING=$NEXT_PUBLIC_MEMECHAN_PROGRAM_ID_STAKING
ENV CHART_CONTRACT_NAME=$CHART_CONTRACT_NAME

COPY . .
RUN bun run build

FROM node:20-alpine AS runner

WORKDIR /app

RUN apk add --no-cache libusb eudev-libs

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/ws ./node_modules/ws
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]
