namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_MEMECHAN_PROGRAM_ID: string;
    NEXT_PUBLIC_MEMECHAN_PROGRAM_ID_V2: string;
    NEXT_PUBLIC_BE_URL: string;
    NEXT_PUBLIC_CHART_HISTORICAL_PRICES_ENDPOINT: string;
    NEXT_PUBLIC_CHART_CURRENT_PRICE_ENDPOINT: string;
    NEXT_PUBLIC_CHART_HISTORICAL_PRICES_ENDPOINT: string;
    NEXT_PUBLIC_CHART_PRICE_DIGITS_AFTER_COMMA: string;
    NEXT_PUBLIC_CHART_REALTIME_RELOAD_INTERVAL: number;
    CHART_CONTRACT_NAME: string;
    NPM_TOKEN: string;
  }
}
